server:
  port: 8181

spring:
  redis:
    # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
    url: redis://localhost:6379
    database: 0
    # 链接或者读取超时
    timeout: 2s
  dubbo:
    application:
      name: merchant-console
    registry:
      address: zookeeper://127.0.0.1:2181

zc:
  merchant:
    token-ttl: 60
