server:
  port: 8383
#  ssl:
#    enabled: true
#    key-alias: meepai
#    key-store: classpath:meepai.keystore
#    key-store-type: JKS
#    key-store-password: meepai123
#  port: 8443
#  http:
#    port: 8080

spring:
  redis:
    # Connection URL, will override host, port and password (user will be ignored), e.g. redis://user:password@example.com:6379
    url: redis://localhost:6379
    database: 0
    # 链接或者读取超时
    timeout: 2s
  dubbo:
    application:
      name: manager-console
    registry:
      address: zookeeper://127.0.0.1:2181

zc:
  manager:
    token-ttl: 60
